
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wifcukhtssicphdfrtex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpZmN1a2h0c3NpY3BoZGZydGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MTk5NDYsImV4cCI6MjA1NDQ5NTk0Nn0.Bnjw3wqk2rsJL1D1sr3sm8QRSkFPKoyxWM2Y7eRisCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      // Set session expiry to 24 hours (in seconds)
      flowType: 'pkce',
      storageKey: 'saahitt-guest-manager-session'
    }
  }
);

// Handle session refresh and expiry
supabase.auth.onAuthStateChange((event, session) => {
  // Check if session exists and when it was created
  if (session) {
    const sessionCreatedAt = new Date(session.created_at).getTime();
    const currentTime = new Date().getTime();
    const dayInMs = 24 * 60 * 60 * 1000;
    
    // If session is older than 24 hours, sign out the user
    if (currentTime - sessionCreatedAt > dayInMs) {
      console.log('Session expired (older than 24 hours). Signing out...');
      supabase.auth.signOut();
    }
  }
});
